-- Universidad Tecnica de Ambato
-- Facultad de Ingenieria en Sistemas
-- Asignatura: Base de Datos
-- Docente: Jose Caiza
-- Formato: APA 7
-- Ejercicios de Implementacion - Oracle

/* =========================================================
   EJERCICIO 1: SISTEMA DE INVENTARIO ACADEMICO
   Objetivo: DDL, restricciones, claves foraneas y recuperacion
   ========================================================= */

CREATE USER INVENTARIO IDENTIFIED BY INVENTARIO123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO INVENTARIO;
GRANT CREATE TABLE TO INVENTARIO;
GRANT CREATE VIEW TO INVENTARIO;
GRANT CREATE SEQUENCE TO INVENTARIO;
GRANT CREATE SYNONYM TO INVENTARIO;
GRANT RESOURCE, CONNECT TO INVENTARIO;

CONNECT INVENTARIO/INVENTARIO123;

-- FASE P1: Tablas base
CREATE TABLE CATEGORIA (
    ID_CAT NUMBER(10) PRIMARY KEY,
    NOM_CAT VARCHAR2(25) NOT NULL,
    DES_CAT VARCHAR2(80)
);

CREATE TABLE DEPARTAMENTO (
    ID_DEP NUMBER(10) PRIMARY KEY,
    NOM_DEP VARCHAR2(20) NOT NULL,
    DES_DEP VARCHAR2(80)
);

CREATE TABLE ESTADO_ARTICULO (
    ID_EST NUMBER(10) PRIMARY KEY,
    NOM_EST VARCHAR2(20) NOT NULL,
    DES_EST VARCHAR2(80)
);

-- FASE P2: Tablas con restricciones y relaciones iniciales
CREATE TABLE ROL (
    ID_ROL NUMBER(10) PRIMARY KEY,
    NOM_ROL VARCHAR2(20) NOT NULL,
    DES_ROL VARCHAR2(80)
);

CREATE TABLE USUARIO (
    ID_USU NUMBER(10) PRIMARY KEY,
    NOM_USU VARCHAR2(20) NOT NULL,
    APE_USU VARCHAR2(20) NOT NULL,
    COR_USU VARCHAR2(40) NOT NULL UNIQUE,
    EST_USU VARCHAR2(15) NOT NULL CHECK (EST_USU IN ('ACTIVO', 'INACTIVO')),
    ID_ROL_USU NUMBER(10) NOT NULL,
    FOREIGN KEY (ID_ROL_USU) REFERENCES ROL(ID_ROL)
);

CREATE TABLE UBICACION (
    ID_UBI NUMBER(10) PRIMARY KEY,
    NOM_UBI VARCHAR2(20) NOT NULL,
    TIP_UBI VARCHAR2(20) NOT NULL,
    DES_UBI VARCHAR2(80),
    ID_DEP_PER NUMBER(10) NOT NULL,
    FOREIGN KEY (ID_DEP_PER) REFERENCES DEPARTAMENTO(ID_DEP)
);

CREATE TABLE RESPONSABLE (
    ID_RES NUMBER(10) PRIMARY KEY,
    NOM_RES VARCHAR2(20) NOT NULL,
    APE_RES VARCHAR2(20) NOT NULL,
    TIP_RES VARCHAR2(30),
    TEL_RES VARCHAR2(10)
);

-- FASE P3: Tabla principal y relaciones con claves foraneas
CREATE TABLE ARTICULO (
    ID_ART NUMBER(10) PRIMARY KEY,
    NOM_ART VARCHAR2(50) NOT NULL,
    DES_ART VARCHAR2(80),
    CANT_ART NUMBER(10) NOT NULL,
    PRECIO_ART NUMBER(10,2) NOT NULL,
    ID_CAT NUMBER(10) NOT NULL,
    ID_DEP NUMBER(10) NOT NULL,
    ID_EST NUMBER(10) NOT NULL,
    ID_UBI NUMBER(10) NOT NULL,
    ID_RES NUMBER(10) NOT NULL,
    CONSTRAINT FK_CAT_ART FOREIGN KEY (ID_CAT) REFERENCES CATEGORIA(ID_CAT),
    CONSTRAINT FK_DEP_ART FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP),
    CONSTRAINT FK_EST_ART FOREIGN KEY (ID_EST) REFERENCES ESTADO_ARTICULO(ID_EST),
    CONSTRAINT FK_UBI_ART FOREIGN KEY (ID_UBI) REFERENCES UBICACION(ID_UBI),
    CONSTRAINT FK_RES_ART FOREIGN KEY (ID_RES) REFERENCES RESPONSABLE(ID_RES)
);

CREATE TABLE PRESTAMO (
    ID_PRE NUMBER(10) PRIMARY KEY,
    ID_ART NUMBER(10) NOT NULL,
    ID_USU NUMBER(10) NOT NULL,
    FEC_PRE DATE NOT NULL,
    FEC_DEV DATE NOT NULL,
    CONSTRAINT FK_ART_PRE FOREIGN KEY (ID_ART) REFERENCES ARTICULO(ID_ART),
    CONSTRAINT FK_USU_PRE FOREIGN KEY (ID_USU) REFERENCES USUARIO(ID_USU),
    CONSTRAINT CK_FECHAS_PRESTAMO CHECK (FEC_DEV >= FEC_PRE)
);

CREATE TABLE DETALLE_PRESTAMO (
    ID_DET_PRE NUMBER(10) PRIMARY KEY,
    ID_PRE NUMBER(10) NOT NULL,
    OBS_DET_PRE VARCHAR2(200) NOT NULL,
    CONSTRAINT FK_PRE_DET FOREIGN KEY (ID_PRE) REFERENCES PRESTAMO(ID_PRE)
);

-- FASE P4: ALTER TABLE, DROP TABLE y FLASHBACK
ALTER TABLE ARTICULO ADD CONSTRAINT CK_CANT_ART CHECK (CANT_ART >= 0);
ALTER TABLE RESPONSABLE ADD COR_RESP VARCHAR2(50);
ALTER TABLE RESPONSABLE 
ADD CONSTRAINT UK_COR_RESP UNIQUE (COR_RESP);
-- Inserciones en tablas base
INSERT INTO CATEGORIA VALUES (1, 'Equipos', 'Equipos de laboratorio');
INSERT INTO DEPARTAMENTO VALUES (1, 'Sistemas', 'Area de sistemas');
INSERT INTO ESTADO_ARTICULO VALUES (1, 'Disponible', 'Articulo disponible para uso');

-- Inserciones en tablas con restricciones
INSERT INTO ROL VALUES (1, 'ADMIN', 'ADMINISTRADOR DEL SISTEMA');
INSERT INTO ROL VALUES (2, 'EJECUTIVO', 'ENCARGADO DEL PERSONAL');

INSERT INTO USUARIO VALUES (1, 'Sebastian', 'Vaca', 'svaca@uta.edu.ec', 'ACTIVO', 1);
INSERT INTO USUARIO VALUES (2, 'Juan', 'Arcos', 'jarcos@uta.edu.ec', 'ACTIVO', 2);
INSERT INTO USUARIO VALUES (3, 'Andrew', 'Lara', 'alara@uta.edu.ec', 'ACTIVO', 1);
INSERT INTO USUARIO VALUES (4, 'Tomas', 'Solis', 'tsolis@uta.edu.ec', 'ACTIVO', 1);

INSERT INTO UBICACION VALUES (1, 'Lab1', 'laboratorio', NULL, 1);
INSERT INTO UBICACION VALUES (2, 'Bodega1', 'almacen', 'Bodega principal', 1);

INSERT INTO RESPONSABLE VALUES (1, 'CARLOS', 'LOPEZ', 'DOCENTE', '0986453492', 'clopez@uta.edu.ec');
INSERT INTO RESPONSABLE VALUES (2, 'MARIA', 'GARCIA', 'COORDINADOR', '0987654321', 'mgarcia@uta.edu.ec');

-- Inserciones en tablas relacionales
INSERT INTO ARTICULO VALUES (1, 'Laptop', 'Equipo para practicas', 5, 850.00, 1, 1, 1, 1, 1);
INSERT INTO ARTICULO VALUES (2, 'Monitor', 'Monitor LED 24', 10, 250.00, 1, 1, 1, 2, 2);

INSERT INTO PRESTAMO VALUES (1, 1, 1, DATE '2026-04-01', DATE '2026-04-08');
INSERT INTO PRESTAMO VALUES (2, 2, 2, DATE '2026-04-02', DATE '2026-04-09');

INSERT INTO DETALLE_PRESTAMO VALUES (1, 1, 'Prestamo por una semana');
INSERT INTO DETALLE_PRESTAMO VALUES (2, 2, 'Prestamo por diez dias');
COMMIT;

-- Consulta con subconsulta: Obtener usuarios con rol ADMIN
SELECT NOM_USU, APE_USU
FROM USUARIO
WHERE ID_ROL_USU IN (
    SELECT ID_ROL
    FROM ROL
    WHERE NOM_ROL = 'ADMIN'
);

-- Prueba de DROP TABLE y FLASHBACK
DROP TABLE DETALLE_PRESTAMO;
FLASHBACK TABLE DETALLE_PRESTAMO TO BEFORE DROP;

-- Consultas de verificacion
SELECT * FROM CATEGORIA;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM ESTADO_ARTICULO;
SELECT * FROM ROL;
SELECT * FROM USUARIO;
SELECT * FROM UBICACION;
SELECT * FROM RESPONSABLE;
SELECT * FROM ARTICULO;
SELECT * FROM PRESTAMO;
SELECT * FROM DETALLE_PRESTAMO;

/* =========================================================
     EJERCICIO 2: SISTEMA DE BIBLIOTECA
     Objetivo: Implementar un sistema con relaciones, restricciones
                         y pruebas de integridad.
     INSTRUCCIÓN: Ejecute este bloque conectado como el propietario
     (por ejemplo: BIBLIOTECA). No requiere triggers ni secuencias.
     ========================================================= */
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO BIBLIOTECA;
GRANT CREATE TABLE TO BIBLIOTECA;
GRANT CREATE VIEW TO BIBLIOTECA;
GRANT CREATE SEQUENCE TO BIBLIOTECA;
GRANT CREATE SYNONYM TO BIBLIOTECA;
GRANT RESOURCE, CONNECT TO BIBLIOTECA;

-- FASE P1: Crear tablas base
CREATE TABLE ARTICULO (
        ID_ART NUMBER(10) PRIMARY KEY,
        NOMBRE VARCHAR2(100) NOT NULL
);

CREATE TABLE PRESTAMO (
        ID_PRE NUMBER(10) PRIMARY KEY,
        FECHA DATE NOT NULL
);

CREATE TABLE DETALLE_PRESTAMO (
        ID_DET NUMBER(10) PRIMARY KEY,
        ID_PRE NUMBER(10) NOT NULL,
        ID_ART NUMBER(10) NOT NULL,
        CANTIDAD NUMBER(10) NOT NULL,
        CONSTRAINT FK_DET_PRE FOREIGN KEY (ID_PRE)
                REFERENCES PRESTAMO(ID_PRE) ON DELETE CASCADE,
        CONSTRAINT FK_DET_ART FOREIGN KEY (ID_ART)
                REFERENCES ARTICULO(ID_ART)
);
INSERT INTO DETALLE_PRESTAMO (ID_DET, ID_PRE, ID_ART, CANTIDAD) VALUES (1, 2, 1, 2);
INSERT INTO DETALLE_PRESTAMO (ID_DET, ID_PRE, ID_ART, CANTIDAD) VALUES (2, 2, 1, 1);
INSERT INTO DETALLE_PRESTAMO (ID_DET, ID_PRE, ID_ART, CANTIDAD) VALUES (3, 2, 1, 1);

-- FASE P2: Aplicar restricciones adicionales
ALTER TABLE ARTICULO ADD CONSTRAINT UQ_ART_NOMBRE UNIQUE (NOMBRE);
ALTER TABLE DETALLE_PRESTAMO ADD CONSTRAINT CK_CANT_POS CHECK (CANTIDAD > 0);

-- FASE P3: Implementar relaciones (inserciones de prueba con IDs explícitos)
INSERT INTO ARTICULO (ID_ART, NOMBRE) VALUES (1, 'Libro A');
INSERT INTO ARTICULO (ID_ART, NOMBRE) VALUES (2, 'Libro B');
INSERT INTO PRESTAMO (ID_PRE, FECHA) VALUES (1, SYSDATE);
INSERT INTO DETALLE_PRESTAMO (ID_DET, ID_PRE, ID_ART, CANTIDAD)
VALUES (1, 1, 1, 2);
COMMIT;

-- Consultas de verificación
SELECT * FROM ARTICULO;
SELECT * FROM PRESTAMO;
SELECT * FROM DETALLE_PRESTAMO;

-- Probar integridad referencial: al borrar el préstamo, se deben borrar detalles
DELETE FROM PRESTAMO WHERE ID_PRE = 1;
SELECT * FROM DETALLE_PRESTAMO;

-- FASE P4: Evolución del esquema y recuperación
ALTER TABLE ARTICULO ADD (ESTADO_LIBRO VARCHAR2(20) DEFAULT 'DISPONIBLE' NOT NULL);

-- IMPORTANTE: Para que FLASHBACK funcione, RECYCLEBIN debe estar habilitado a nivel de BD.
-- Si aún no está habilitado, ejecute como DBA/SYSDBA:
-- ALTER SYSTEM SET db_recovery_file_dest_size = 10G;
-- ALTER SYSTEM SET db_recovery_file_dest = '<ruta>';
-- O simplemente: ALTER DATABASE ARCHIVELOG;
-- Y luego en la sesión del usuario: PURGE RECYCLEBIN; (limpia la papelera primero)

-- Limpiar papelera antes de la prueba
PURGE RECYCLEBIN;

-- Demostración de DROP TABLE y FLASHBACK
DROP TABLE DETALLE_PRESTAMO;
FLASHBACK TABLE DETALLE_PRESTAMO TO BEFORE DROP;

-- Consultas finales
SELECT * FROM ARTICULO;
SELECT * FROM PRESTAMO;
SELECT * FROM DETALLE_PRESTAMO;