
SET DEFINE OFF;

-- ---------------------------------------------------------
-- Limpieza opcional
-- ---------------------------------------------------------
-- Ejecutar solo si deseas recrear el esquema completo.
-- DROP VIEW vw_articulo_disponible;
-- DROP TABLE mantenimiento CASCADE CONSTRAINTS PURGE;
-- DROP TABLE detalle_prestamo CASCADE CONSTRAINTS PURGE;
-- DROP TABLE prestamo CASCADE CONSTRAINTS PURGE;
-- DROP TABLE movimiento CASCADE CONSTRAINTS PURGE;
-- DROP TABLE notificacion CASCADE CONSTRAINTS PURGE;
-- DROP TABLE auditoria CASCADE CONSTRAINTS PURGE;
-- DROP TABLE articulo CASCADE CONSTRAINTS PURGE;
-- DROP TABLE usuario CASCADE CONSTRAINTS PURGE;
-- DROP TABLE rol CASCADE CONSTRAINTS PURGE;
-- DROP TABLE estado CASCADE CONSTRAINTS PURGE;
-- DROP TABLE categoria CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ubicacion CASCADE CONSTRAINTS PURGE;
-- DROP TABLE departamento CASCADE CONSTRAINTS PURGE;

-- ---------------------------------------------------------
-- Catálogos base
-- ---------------------------------------------------------

CREATE TABLE departamento (
  id_dep        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom_dep       VARCHAR2(120) NOT NULL,
  des_dep       VARCHAR2(300),
  fec_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_departamento PRIMARY KEY (id_dep),
  CONSTRAINT uq_departamento_nom UNIQUE (nom_dep),
  CONSTRAINT ck_departamento_nom CHECK (TRIM(nom_dep) IS NOT NULL)
);

CREATE TABLE ubicacion (
  id_ubi        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom_ubi       VARCHAR2(120) NOT NULL,
  des_ubi       VARCHAR2(300),
  id_dep        NUMBER NOT NULL,
  fec_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_ubicacion PRIMARY KEY (id_ubi),
  CONSTRAINT uq_ubicacion_nom_dep UNIQUE (nom_ubi, id_dep),
  CONSTRAINT ck_ubicacion_nom CHECK (TRIM(nom_ubi) IS NOT NULL),
  CONSTRAINT fk_ubicacion_departamento FOREIGN KEY (id_dep)
    REFERENCES departamento (id_dep)
);

CREATE TABLE rol (
  id_rol        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom_rol       VARCHAR2(80) NOT NULL,
  des_rol       VARCHAR2(300),
  est_rol       NUMBER(1) DEFAULT 1 NOT NULL,
  fec_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_rol PRIMARY KEY (id_rol),
  CONSTRAINT uq_rol_nom UNIQUE (nom_rol),
  CONSTRAINT ck_rol_estado CHECK (est_rol IN (0, 1))
);

CREATE TABLE categoria (
  id_cat        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom_cat       VARCHAR2(120) NOT NULL,
  des_cat       VARCHAR2(300),
  fec_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_categoria PRIMARY KEY (id_cat),
  CONSTRAINT uq_categoria_nom UNIQUE (nom_cat),
  CONSTRAINT ck_categoria_nom CHECK (TRIM(nom_cat) IS NOT NULL)
);

CREATE TABLE estado (
  id_est        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom_est       VARCHAR2(80) NOT NULL,
  des_est       VARCHAR2(300),
  tipo_est      VARCHAR2(40) NOT NULL,
  fec_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_estado PRIMARY KEY (id_est),
  CONSTRAINT uq_estado_nom_tipo UNIQUE (nom_est, tipo_est),
  CONSTRAINT ck_estado_tipo CHECK (
    tipo_est IN ('ACTIVO', 'ARTICULO', 'PRESTAMO', 'MOVIMIENTO', 'MANTENIMIENTO', 'NOTIFICACION')
  )
);

-- ---------------------------------------------------------
-- Seguridad / usuarios
-- ---------------------------------------------------------

CREATE TABLE usuario (
  id_usr        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom_usr       VARCHAR2(120) NOT NULL,
  ape_usr       VARCHAR2(120) NOT NULL,
  cor_usr       VARCHAR2(180) NOT NULL,
  tel_usr       VARCHAR2(30),
  usu_login     VARCHAR2(80) NOT NULL,
  pass_hash     VARCHAR2(255) NOT NULL,
  est_usr       NUMBER(1) DEFAULT 1 NOT NULL,
  id_rol        NUMBER NOT NULL,
  id_dep        NUMBER,
  id_ubi        NUMBER,
  fec_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_usuario PRIMARY KEY (id_usr),
  CONSTRAINT uq_usuario_correo UNIQUE (cor_usr),
  CONSTRAINT uq_usuario_login UNIQUE (usu_login),
  CONSTRAINT ck_usuario_estado CHECK (est_usr IN (0, 1)),
  CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol)
    REFERENCES rol (id_rol),
  CONSTRAINT fk_usuario_departamento FOREIGN KEY (id_dep)
    REFERENCES departamento (id_dep),
  CONSTRAINT fk_usuario_ubicacion FOREIGN KEY (id_ubi)
    REFERENCES ubicacion (id_ubi)
);

-- ---------------------------------------------------------
-- Inventario
-- ---------------------------------------------------------

CREATE TABLE articulo (
  id_art        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom_art       VARCHAR2(180) NOT NULL,
  des_art       VARCHAR2(500),
  ser_art       VARCHAR2(100),
  mar_art       VARCHAR2(80),
  mod_art       VARCHAR2(80),
  can_art       NUMBER DEFAULT 1 NOT NULL,
  val_art       NUMBER(12,2) DEFAULT 0 NOT NULL,
  est_art       NUMBER(1) DEFAULT 1 NOT NULL,
  id_cat        NUMBER NOT NULL,
  id_est        NUMBER NOT NULL,
  id_dep        NUMBER,
  id_ubi        NUMBER,
  fec_registro  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_articulo PRIMARY KEY (id_art),
  CONSTRAINT uq_articulo_serial UNIQUE (ser_art),
  CONSTRAINT ck_articulo_cantidad CHECK (can_art >= 0),
  CONSTRAINT ck_articulo_valor CHECK (val_art >= 0),
  CONSTRAINT ck_articulo_estado CHECK (est_art IN (0, 1)),
  CONSTRAINT fk_articulo_categoria FOREIGN KEY (id_cat)
    REFERENCES categoria (id_cat),
  CONSTRAINT fk_articulo_estado FOREIGN KEY (id_est)
    REFERENCES estado (id_est),
  CONSTRAINT fk_articulo_departamento FOREIGN KEY (id_dep)
    REFERENCES departamento (id_dep),
  CONSTRAINT fk_articulo_ubicacion FOREIGN KEY (id_ubi)
    REFERENCES ubicacion (id_ubi)
);

-- ---------------------------------------------------------
-- Prestamos
-- ---------------------------------------------------------

CREATE TABLE prestamo (
  id_pres       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  fec_pres      DATE DEFAULT SYSDATE NOT NULL,
  fec_entrega   DATE,
  fec_devolucion DATE,
  obs_pres      VARCHAR2(500),
  est_pres      NUMBER(1) DEFAULT 1 NOT NULL,
  id_usr        NUMBER NOT NULL,
  id_est        NUMBER NOT NULL,
  CONSTRAINT pk_prestamo PRIMARY KEY (id_pres),
  CONSTRAINT ck_prestamo_estado CHECK (est_pres IN (0, 1)),
  CONSTRAINT ck_prestamo_fechas CHECK (fec_devolucion IS NULL OR fec_devolucion >= fec_pres),
  CONSTRAINT fk_prestamo_usuario FOREIGN KEY (id_usr)
    REFERENCES usuario (id_usr),
  CONSTRAINT fk_prestamo_estado FOREIGN KEY (id_est)
    REFERENCES estado (id_est)
);

CREATE TABLE detalle_prestamo (
  id_pre       NUMBER NOT NULL,
  id_art       NUMBER NOT NULL,
  can_pre      NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT pk_detalle_prestamo PRIMARY KEY (id_pre, id_art),
  CONSTRAINT ck_detalle_prestamo_cantidad CHECK (can_pre > 0),
  CONSTRAINT fk_detalle_prestamo_prestamo FOREIGN KEY (id_pre)
    REFERENCES prestamo (id_pres)
    ON DELETE CASCADE,
  CONSTRAINT fk_detalle_prestamo_articulo FOREIGN KEY (id_art)
    REFERENCES articulo (id_art)
);

-- ---------------------------------------------------------
-- Movimientos, mantenimiento, notificaciones y auditoría
-- ---------------------------------------------------------

CREATE TABLE movimiento (
  id_mov        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  tip_mov       VARCHAR2(40) NOT NULL,
  fec_mov       DATE DEFAULT SYSDATE NOT NULL,
  obs_mov       VARCHAR2(500),
  id_art        NUMBER NOT NULL,
  id_usr        NUMBER NOT NULL,
  id_ubi_ori    NUMBER,
  id_ubi_des    NUMBER,
  CONSTRAINT pk_movimiento PRIMARY KEY (id_mov),
  CONSTRAINT ck_movimiento_tipo CHECK (tip_mov IN ('INGRESO', 'SALIDA', 'TRASLADO', 'BAJA', 'AJUSTE', 'PRESTAMO')),
  CONSTRAINT fk_movimiento_articulo FOREIGN KEY (id_art)
    REFERENCES articulo (id_art),
  CONSTRAINT fk_movimiento_usuario FOREIGN KEY (id_usr)
    REFERENCES usuario (id_usr),
  CONSTRAINT fk_movimiento_ubi_ori FOREIGN KEY (id_ubi_ori)
    REFERENCES ubicacion (id_ubi),
  CONSTRAINT fk_movimiento_ubi_des FOREIGN KEY (id_ubi_des)
    REFERENCES ubicacion (id_ubi),
  CONSTRAINT ck_movimiento_origen_destino CHECK (id_ubi_ori IS NULL OR id_ubi_des IS NULL OR id_ubi_ori <> id_ubi_des)
);

CREATE TABLE mantenimiento (
  id_man        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  des_man       VARCHAR2(300) NOT NULL,
  tip_man       VARCHAR2(60) NOT NULL,
  fec_ini       DATE DEFAULT SYSDATE NOT NULL,
  fec_fin       DATE,
  obs_man       VARCHAR2(500),
  est_man       NUMBER(1) DEFAULT 1 NOT NULL,
  id_art        NUMBER NOT NULL,
  id_usr        NUMBER NOT NULL,
  id_est        NUMBER NOT NULL,
  CONSTRAINT pk_mantenimiento PRIMARY KEY (id_man),
  CONSTRAINT ck_mantenimiento_estado CHECK (est_man IN (0, 1)),
  CONSTRAINT ck_mantenimiento_fechas CHECK (fec_fin IS NULL OR fec_fin >= fec_ini),
  CONSTRAINT fk_mantenimiento_articulo FOREIGN KEY (id_art)
    REFERENCES articulo (id_art),
  CONSTRAINT fk_mantenimiento_usuario FOREIGN KEY (id_usr)
    REFERENCES usuario (id_usr),
  CONSTRAINT fk_mantenimiento_estado FOREIGN KEY (id_est)
    REFERENCES estado (id_est)
);

CREATE TABLE notificacion (
  id_not        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  tit_not       VARCHAR2(120) NOT NULL,
  men_not       VARCHAR2(1000) NOT NULL,
  fec_not       DATE DEFAULT SYSDATE NOT NULL,
  est_not       NUMBER(1) DEFAULT 1 NOT NULL,
  id_usr        NUMBER NOT NULL,
  CONSTRAINT pk_notificacion PRIMARY KEY (id_not),
  CONSTRAINT ck_notificacion_estado CHECK (est_not IN (0, 1)),
  CONSTRAINT fk_notificacion_usuario FOREIGN KEY (id_usr)
    REFERENCES usuario (id_usr)
    ON DELETE CASCADE
);

CREATE TABLE auditoria (
  id_aud        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nom_tabla     VARCHAR2(80) NOT NULL,
  id_registro   VARCHAR2(80),
  nom_accion    VARCHAR2(20) NOT NULL,
  nom_usuario   VARCHAR2(80) NOT NULL,
  fec_aud       DATE DEFAULT SYSDATE NOT NULL,
  des_aud       VARCHAR2(1000),
  CONSTRAINT pk_auditoria PRIMARY KEY (id_aud),
  CONSTRAINT ck_auditoria_accion CHECK (nom_accion IN ('INSERT', 'UPDATE', 'DELETE'))
);

-- ---------------------------------------------------------
-- Índices recomendados
-- ---------------------------------------------------------

CREATE INDEX idx_ubicacion_departamento ON ubicacion (id_dep);
CREATE INDEX idx_usuario_rol ON usuario (id_rol);
CREATE INDEX idx_usuario_departamento ON usuario (id_dep);
CREATE INDEX idx_usuario_ubicacion ON usuario (id_ubi);
CREATE INDEX idx_articulo_categoria ON articulo (id_cat);
CREATE INDEX idx_articulo_estado ON articulo (id_est);
CREATE INDEX idx_articulo_departamento ON articulo (id_dep);
CREATE INDEX idx_articulo_ubicacion ON articulo (id_ubi);
CREATE INDEX idx_prestamo_usuario ON prestamo (id_usr);
CREATE INDEX idx_movimiento_fecha ON movimiento (fec_mov);
CREATE INDEX idx_notificacion_usuario ON notificacion (id_usr);

-- ---------------------------------------------------------
-- Vistas útiles
-- ---------------------------------------------------------

CREATE OR REPLACE VIEW vw_articulo_disponible AS
SELECT
  a.id_art,
  a.nom_art,
  a.des_art,
  a.ser_art,
  a.mar_art,
  a.mod_art,
  a.can_art,
  c.nom_cat,
  e.nom_est,
  d.nom_dep,
  u.nom_ubi
FROM articulo a
JOIN categoria c ON c.id_cat = a.id_cat
JOIN estado e ON e.id_est = a.id_est
LEFT JOIN departamento d ON d.id_dep = a.id_dep
LEFT JOIN ubicacion u ON u.id_ubi = a.id_ubi
WHERE a.est_art = 1;

CREATE OR REPLACE VIEW vw_usuario_seguridad AS
SELECT
  u.id_usr,
  u.nom_usr,
  u.ape_usr,
  u.cor_usr,
  u.tel_usr,
  u.usu_login,
  u.est_usr,
  r.nom_rol,
  d.nom_dep,
  ub.nom_ubi
FROM usuario u
JOIN rol r ON r.id_rol = u.id_rol
LEFT JOIN departamento d ON d.id_dep = u.id_dep
LEFT JOIN ubicacion ub ON ub.id_ubi = u.id_ubi;

-- ---------------------------------------------------------
-- Usuario de esquema y permisos
-- ---------------------------------------------------------

-- Ejecutar como SYS, SYSTEM o un usuario con privilegios de administración.
-- Ajusta el tablespace si tu entorno usa otro nombre distinto de USERS.

CREATE USER gestionfisei IDENTIFIED BY gestionfisei
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO gestionfisei;
GRANT CREATE TABLE TO gestionfisei;
GRANT CREATE SEQUENCE TO gestionfisei;
GRANT CREATE VIEW TO gestionfisei;
GRANT CREATE TRIGGER TO gestionfisei;
GRANT CREATE PROCEDURE TO gestionfisei;
GRANT CREATE SYNONYM TO gestionfisei;

-- ---------------------------------------------------------
-- Observaciones de implementación
-- ---------------------------------------------------------
-- 1. Los nombres usan prefijos consistentes para facilitar mantenimiento.
-- 2. Se incluyen UNIQUE, CHECK y FK para proteger la integridad.
-- 3. Si deseas autenticación con hashing real, guarda en pass_hash un hash seguro y nunca texto plano.
-- 4. Para Oracle 11g o inferior, reemplaza IDENTITY por SEQUENCE + TRIGGER.

COMMIT;
